#!/bin/bash
#
# Picture Streamer
#
# This file is part of the Picture Streamer project.
# The program streams image previews from your DSLR or simular
# camera to a web interface, allowing you to download pictures
# the moment they've been taken.
#
# Copyright (C) 2015 Christian Beuschel <chris109@web.de>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software Foundation,
# Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA

nohup python picture-streamer.py -session  "default_capture_session" \
                           -shutdown "sudo shutdown -h now" \
                           -reboot   "sudo reboot" \
                           -log      "default_capture_session.log" 0<&- &>/dev/null &
